### ISSUE TITLE
no TTY (-t) detected garrysmod-gmod-1  | Steam needs it. Exit.

### ISSUE THREAD

**Issue by owojcikiewicz** [Hackebein/docker-garrysmod#15]
Hi, I'm trying to run a Garry's Mod server alongside a MySQL database in docker compose.

I'm getting these errors: `garrysmod-gmod-1  | no TTY (-t) detected` and `garrysmod-gmod-1  | Steam needs it. Exit.`

Here's my `docker-compose` file: 
```
version: '3.3'
services:
    gmod:
        ports:
            - '27015:27015/udp'
            - '27015:27015'
            - '27005:27005/udp'
        volumes:
            - '$PWD/addons:/home/gmod/server/garrysmod/addons'
            - '$PWD/darkrp:/home/gmod/server/garrysmod/gamemodes/darkrp'
            - '$PWD/lua:/home/gmod/server/garrysmod/lua'
            - '/home/gmod/server'
        environment:
            - AUTHKEY=XXXXXXXXXXXXXXXXXXXXXXXX
            - GSLT=XXXXXXXXXXXXXXXXXXXXXXXX
            - GAMEMODE=sandbox
            - MAP=gm_construct
            - MAXPLAYERS=4
        image: hackebein/garrysmod
    db:
        image: mariadb:10.4
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - '3306:3306'
volumes:
    db_data:
    addons:
    gamemodes:
    lua:
```

**Comment by Hackebein** [comment]
you are missing `tty: true`
checkout https://docs.docker.com/compose/compose-file/compose-file-v3/#domainname-hostname-ipc-mac_address-privileged-read_only-shm_size-stdin_open-tty-user-working_dir

**Comment by owojcikiewicz** [comment]
Thanks a lot for your help! 

The server seems to work properly but I can't connect . Any idea why this would happen?

**Comment by Hackebein** [comment]
without any indicator. Sadly not

**Comment by owojcikiewicz** [comment]
I can see that the server is running in the console but I can't connect. I'm getting a connection failed after x retries. Docker is running via WSL, if that's of any help. Ports should be exposed. 

This is my updated docker-compose:
```yml
version: '3.3'
services:
    gmod:
        container_name: gmod
        image: hackebein/garrysmod
        environment:
            - GSLT=${GMOD_GSLT}
            - GAMEMODE=${GMOD_GAMEMODE}
            - MAP=${GMOD_MAP}
            - MAXPLAYERS=${GMOD_MAXPLAYERS} 
            - TICKRATE=${GMOD_TICKRATE}
        volumes:
            - ./addons:/opt/steam/garrysmod/addons
            - ./darkrp:/opt/steam/garrysmod/gamemodes/darkrp
            - ./binaries:/opt/steam/garrysmod/lua/bin
            - steam_data:/opt/steam
        ports:
            - 27015:27015/udp
            - 27015:27015
            - 27005:27005/udp
        tty: true
    db:
        container_name: db
        image: mariadb:10.4
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - 3306:3306
volumes:
    db_data:
    steam_data:
```
