### ISSUE TITLE
Server stuck at the "Network: ..." line

### ISSUE THREAD

**Issue by Slebby** [Hackebein/docker-garrysmod#18]
Hi, I tried to start the server but it ends up stuck at the "Network: ..." line. I believe the output should end up with VAC secure mode.

Here is the output when i start the server:

```
************** WARNING ***************
Running the dedicated server as root  
is highly discouraged. It is generally
unnecessary to use root privileges to 
execute the dedicated server.         
**************************************


Auto detecting CPUntinue to launch in 1 secondss
Using default binary: ./srcds_linux
Server will auto-restart if there is a crash.
mount.cfg adding path: '/opt/steam/Steam'
mount.cfg adding path: '/opt/steam/cstrike'
mount.cfg adding path: '/opt/steam/hl2'
mount.cfg adding path: '/opt/steam/linux64'
Game_srv.so loaded for "Garry's Mod"
Setting breakpad minidump AppID = 4000
Initializing Steam libraries for Workshop..
[S_API] SteamAPI_Init(): Loaded local 'steamclient.so' OK.
CAppInfoCacheReadFromDiskThread took 0 milliseconds to initialize
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561197960265728 [API loaded no]
[S_API FAIL] Tried to access Steam interface SteamUser023 before SteamAPI_Init succeeded.
WS: No +host_workshop_collection or it is invalid!
Unknown command "cl_cmdrate"
Unknown command "cl_updaterate"
Unknown command "rate"
WARNING: Port 27015 was unavailable - bound to port 27016 instead
WARNING: Port 27005 was unavailable - bound to port 27006 instead
WARNING: Port 27020 was unavailable - bound to port 27021 instead
Network: IP 172.25.0.2, mode MP, dedicated Yes, ports 27016 SV / 27006 CL
_            <== When it reached to this point, it ends up not doing anything

```

Also, here is my docker compose file (the format might be a bit confusing due to that I use CasaOS):

```
name: reverent_chorok
services:
  main_app:
    cpu_shares: 90
    command: []
    container_name: garrys-mod-server
    deploy:
      resources:
        limits:
          memory: 31972M
    environment:
      - AUTHKEY=(removed)
      - MAP=gm_genesis
      - MAXPLAYERS=4
      - WORKSHOP=3297227676
      - WORKSHOPDL=3297227676
    hostname: garrys-mod-server
    image: hackebein/garrysmod:latest
    labels:
      icon: https://icon.casaos.io/main/all/garrysmod.png
    ports:
      - target: 27015
        published: "27015"
        protocol: ""
      - target: 27016
        published: "27016"
        protocol: ""
    restart: unless-stopped
    volumes:
      - type: bind
        source: /mnt/Storage1/CasaShare/garry-mod-server
        target: /opt/steam
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://icon.casaos.io/main/all/garrysmod.png
  index: /
  is_uncontrolled: false
  port_map: ""
  scheme: http
  store_app_id: reverent_chorok
  title:
    custom: Garry's Mod Server
```
